-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.4.0
    hooks:
    -   id: trailing-whitespace
        exclude: \.html$
    -   id: end-of-file-fixer
        exclude: \.html$
    -   id: check-json
    -   id: check-yaml
    -   id: debug-statements
    -   id: requirements-txt-fixer
    -   id: flake8
        exclude: \/migrations\/
-   repo: https://github.com/pre-commit/pre-commit
    rev: v1.11.0
    hooks:
    -   id: validate_manifest
